### ISSUE TITLE
EC2 compatibility

### ISSUE THREAD

**Issue by dmarvp** [bespoken/circle-deploy#11]
### Description
Make the needed changes so that we can deploy our Services and TaskDefinitions to an ECS Cluster with EC2 Container Instances. For this ticket, we are assuming the EC2 Container instances have already been launched inside the target cluster.

The two main changes involve:
- Changing the service `launchType` property to EC2.
- Changing the task definition `requiredCompatibilities` property to EC2.

**Comment by bespoken-cookbook** [comment]
Closed via #9
