### ISSUE TITLE
Add an EC2 instance

### ISSUE THREAD

**Issue by dmarvp** [bespoken/circle-deploy#12]
### Description
We want to be able to create EC2 container instances inside an ECS cluster. For that, we would call a command like this:

```bash
fargate ec2-instance \
--imageId ami-xxxxxxxx \
--instanceCount 1 \
--instanceType t3.micro
--keyPair MyKeyPair 
```

In order to make this work we should
- Create a new class called EC2Manager
- Call the runInstances method of the EC2 class on the AWS SDK
- Assign the AMI, type, number of instances (count), security group, subnet-id, etc
- To add it to the correct cluster we need to set the cluster name on the user data property like this:

```
#!/bin/bash
echo ECS_CLUSTER=${cluster} >> /etc/ecs/ecs.config
```
- We should try to see if we can use the clusterArn in there as opposed to the cluster name. Otherwise, #10 should be deleted.

Defaults to add to our secrets manager:
```
imageId ami: ami-00dc79254d0461090
count: 1
instance-type: t3.micro
keyPair: TBD
```

Things we should set from our secrets manager:
```
security-group-ids sg-903004f8 
subnet-id subnet-6e7f829e
```

### References
- Selected AMI on [AWS Marketplace](https://aws.amazon.com/marketplace/pp/B07KMLLN73?ref=cns_srchrow)
- EC2 runIntances sdk reference: [link](https://docs.aws.amazon.com/AWSJavaScriptSDK/latest/AWS/EC2.html#runInstances-property)
- Launching an ECS Container instance: [Launching an Amazon ECS Container Instance](https://docs.aws.amazon.com/AmazonECS/latest/developerguide/launch_container_instance.html)
  - Step 9 details why we need to modify the userData property.

**Comment by dmarvp** [comment]
@jkelvie let me know if this aligns with what you were thinking for EC2 instances creation.

**Comment by jkelvie** [comment]
@dmarvp , this looks exactly right to me. You highlighted the key trick, which is setting the userData parameter to ensure that the instance joins the correct cluster.

**Comment by dmarvp** [comment]
The right ami to use was actually: ami-09edd32d9b0990d49
